default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: racunko_development

test:
  <<: *default
  database: racunko_test

production:
  <<: *default
  database: racunko_production
  username: racunko
  password: <%= ENV['RACUNKO_DATABASE_PASSWORD'] %>
