default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: racunko_development
  port: 5432

test:
  <<: *default
  database: racunko_test
  port: 5432

production:
  <<: *default
  database: racunko_production
  username: racunko
  password: <%= ENV['RACUNKO_DATABASE_PASSWORD'] %>
